### ISSUE TITLE
Webpack version issue

### ISSUE THREAD

**Issue by omsun123** [Codebrahma/React-Chat#31]
Because of older version of webpack following error happening.
`(base) administrator@dolap:~/Documents/trail/React-Chat$ yarn start
yarn run v1.12.3
$ webpack-dev-server --mode development --open --hot
/home/administrator/Documents/trail/React-Chat/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/administrator/Documents/trail/React-Chat/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at Object.<anonymous> (/home/administrator/Documents/trail/React-Chat/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:25)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
`

**Comment by omsun123** [comment]
This PR resolves the issue https://github.com/Codebrahma/React-Chat/pull/30 . Please review
